version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 80:8000
  elasticsearch:
    image: elasticsearch:7.2.0
    environment:
      - discovery.type=single-node
  postgresql:
    image: postgres:11.4
    environment:
      - POSTGRES_PASSWORD=yolo
      - POSTGRES_USER=stan
      - POSTGRES_DB=stackoverflow-on-the-go
